imports = [ "language.c" ]

[language.c]
compiler = "gcc"
libraries = ["libsForQt5.full", "libsForQt5.kirigami2", "protobuf3_12"]
includes = ["libsForQt5.full", "libsForQt5.kirigami2", "protobuf3_12"]

[devshell]
name = "challah-devshell"
packages = [ "cmake", "binutils" ]

# qbs needs a writable home
[devshell.startup.setTmpHome]
text = """
if [ ! -w "$HOME" ] ; then
	export HOME=/tmp/challah-tmp-build-home/
	mkdir -p $HOME
fi
"""

[devshell.startup.setupQbs]
text = """
qbs setup-toolchains --detect
qbs resolve profile:gcc project.vendoredProtobuf:true
"""
deps = ["setTmpHome"]

# workaround for devshell not setting LIBRARY_PATH
[[env]]
name = "LIBRARY_PATH"
eval = "$DEVSHELL_DIR/lib"

[[commands]]
package = "qbs"
